### ISSUE TITLE
[SpeechToText.ParseRecognizeResponse()][ERROR] & [SpeechToText.OnListenMessage()][ERROR] 

### ISSUE THREAD

**Issue by tiancaipipi110** [watson-developer-cloud/unity-sdk#534]
Hello, out of a sudden, I'm getting these two errors:
```
[03/13/2019 20:07:44][SpeechToText.ParseRecognizeResponse()][ERROR] ParseJsonResponse exception: System.InvalidCastException: Specified cast is not valid.
at IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText.ParseRecognizeResponse (System.Collections.IDictionary resp) [0x003ad] in C:\Users\xxxx\Assets\Watson-2.13.2\Scripts\Services\SpeechToText\v1\SpeechToText.cs:1240
UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:ParseRecognizeResponse(IDictionary) (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:1313)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListenMessage(Message) (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:826)
IBM.Watson.DeveloperCloud.Connection.<ProcessReceiveQueue>d__47:MoveNext() (at Assets/Watson-2.13.2/Scripts/Connection/WSConnector.cs:400)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson-2.13.2/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

```
[03/13/2019 20:07:44][SpeechToText.OnListenMessage()][ERROR] Failed to parse results: {
"results": [
{
"alternatives": [
{
"timestamps": [
[
"tell",
0.91,
1.21
],
[
"me",
1.21,
1.34
],
[
"a",
1.34,
1.47
],
[
"joke",
1.47,
2
]
],
"transcript": "tell me a joke ",
"word_confidence": []
}
],
"final": false
}
],
"result_index": 0
}
UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListenMessage(Message) (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:840)
IBM.Watson.DeveloperCloud.Connection.<ProcessReceiveQueue>d__47:MoveNext() (at Assets/Watson-2.13.2/Scripts/Connection/WSConnector.cs:400)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson-2.13.2/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

I think the first bug should be fixed on issue #349 ? Not sure if this is a new bug? Watson v2.13.2

**Comment by mediumTaj** [comment]
Hi,
This is a casting bug that was fixed in https://github.com/watson-developer-cloud/unity-sdk/pull/533

The `2` in the timestamp of your response is an int and can't automatically be cast to a double. The above PR addresses this by taking the values, converting to string and parsing out the double.

Please update to the latest version of the SDK. Closing this but please comment if this doesn't fix your issue.

**Comment by mediumTaj** [comment]
Duplicate of https://github.com/watson-developer-cloud/unity-sdk/issues/532

**Comment by tiancaipipi110** [comment]
Yes! Thanks!

**Comment by JaimeCastro0926** [comment]
Hello, good evening, I still have the problem, I have not solved it and I already downloaded and installed the latest version, what could it be?

The error happened a few days ago.

Note: I am using it in Spanish.

Error 1
[03/15/2019 02:30:56][SpeechToText.ParseRecognizeResponse()][ERROR] ParseJsonResponse exception: System.InvalidCastException: Cannot cast from source type to destination type.
at Mixspace.Lexicon.Watson.SpeechToText.v1.LexiconSpeechToText.ParseRecognizeResponse (IDictionary resp) [0x0042b]

Error 2
03/15/2019 02:30:56][SpeechToText.OnListenMessage()][ERROR] Failed to parse results: {
"results": [
{
"keywords_result": {},
"alternatives": [
{
"timestamps": [
{
"timestamps": [
[
"poner",
5.17,
5.6
],
[
"carga",
5.6,
5.96
],
[
"positiva",
5.96,
6.53
]
],
"confidence": 0.93,
"transcript": "poner carga positiva ",
"word_confidence": [
[
"poner",
1
],
[
"carga",
0.88
],
[
"positiva",
0.9
]
]
},
{
"transcript": "poner carga positiva un "
},
{
"transcript": "poner carga positiva y "
}
],
"final": true
}
],
"result_index": 1
}
